insert into rules (name) values ('create');
insert into rules (name) values ('read');
insert into rules (name) values ('update');
insert into rules (name) values ('delete');
insert into role (name) values ('super');
insert into role (name) values ('admin');
insert into role (name) values ('user');
insert into role_rules (role_id, rules_id) values (1, 1);
insert into role_rules (role_id, rules_id) values (1, 2);
insert into role_rules (role_id, rules_id) values (1, 3);
insert into role_rules (role_id, rules_id) values (1, 4);
insert into role_rules (role_id, rules_id) values (2, 1);
insert into role_rules (role_id, rules_id) values (2, 2);
insert into role_rules (role_id, rules_id) values (2, 3);
insert into role_rules (role_id, rules_id) values (3, 1);
insert into role_rules (role_id, rules_id) values (3, 2);
insert into users (name, role_id) values ('Samuel', 1);
insert into users (name, role_id) values ('Alexander', 3);
insert into category (name) values ('private');
insert into category (name) values ('public');
insert into state (name) values ('processed');
insert into state (name) values ('completed');
insert into item (name, users_id, category_id, state_id) values ('new_test', 1, 1, 1);
insert into item (name, users_id, category_id, state_id) values ('new_item', 2, 2, 1);
insert into attachs (file_name, item_id) values ('pic.png', 1);
insert into comments (description, item_id) values ('create new item', 2);