insert into vehicle_type (name) values ('car');
insert into vehicle_type (name) values ('truck');
insert into vehicle_type (name) values ('tractor');
insert into vehicle (name, date_of_birth, vehicle_type_id) values ('Moskvich 412', '1975.05.05', 1);
insert into vehicle (name, date_of_birth, vehicle_type_id) values ('LADA Samara', '1990.06.12', 1);
insert into vehicle (name, date_of_birth, vehicle_type_id) values ('KAMAZ 65115', '2005.01.07', 2);
insert into vehicle (name, date_of_birth, vehicle_type_id) values ('ZIL 157', '1978.01.02', 2);
insert into vehicle (name, date_of_birth, vehicle_type_id) values ('K-700', '1984.08.09', 3);
insert into vehicle (name, date_of_birth, vehicle_type_id) values ('T-40', '1979.02.01', 3);
insert into vehicle (name, date_of_birth) values ('Bicycle', '2000.03.06');